/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-01-30 15:12:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("table, tr, th, td {\r\n");
      out.write("padding: 5px;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("th {\r\n");
      out.write("padding: 5px 20px 5px 20px;\r\n");
      out.write("color: white;\r\n");
      out.write("background-color: #6495ED;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\" integrity=\"sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<p><span>Welcome </span>\r\n");
      out.write("   ");
      out.print( request.getParameter("username"));
      out.write("\r\n");
      out.write("</p>\r\n");

int[][] score = {
		{
			35,70,60,90
		},
		{
			30
		},
		{
			32,70,20
		}
};

double[] depPass = new double[3];
int count = 0;

for(int i = 0; i < score.length; i++){
	for(int j = 0; j < score[i].length; j++){
		if(score[i][j] >= 40) {
			count++;
		}
	}
	System.out.println(count + " " + score[i].length);
	depPass[i] = (count*100/score[i].length);
	count = 0;
}


      out.write("\r\n");
      out.write("<table>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <th>Department</th>\r\n");
      out.write("    <th>Student ID</th>\r\n");
      out.write("    <th>Marks</th>\r\n");
      out.write("    <th>Pass %</th>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td rowspan=\"4\" style=\"text-align: center;\">Dep 1</td>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S1')\">S1</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">35</td>\r\n");
      out.write("    <td rowspan=\"4\" style=\"text-align: center;\">");
      out.print( depPass[0]);
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S2')\">S2</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">70</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S3')\">S3</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">60</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S4')\">S4</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">90</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td style=\"text-align: center;\">Dep 2</td>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S5')\">S5</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">30</td>\r\n");
      out.write("    <td style=\"text-align: center;\">");
      out.print( depPass[1]);
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td rowspan=\"3\" style=\"text-align: center;\">Dep 3</td>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S6')\">S6</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">32</td>\r\n");
      out.write("    <td rowspan=\"3\" style=\"text-align: center;\">");
      out.print( depPass[2]);
      out.write("</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S7')\">S7</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">70</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td><a style=\"cursor: pointer; text-decoration: underline; text-decoration-color: blue; color: blue;\" onclick=\"popup('S8')\">S8</a></td>\r\n");
      out.write("    <td style=\"text-align:right\">20</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div id=\"popup\" style = \"top: 150px; left: 150px; position: absolute; z-index: 10; background-color:white; border-style: solid; text-align: center; padding: 10px; width: 50px; display:none;\">\r\n");
      out.write("<div><p id=\"name\"></p></div>\r\n");
      out.write("<div>\r\n");
      out.write("<button class=\"close\">Close</button>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function popup(take){\r\n");
      out.write("	var hidden = $(\"#popup\").is(\":hidden\");\r\n");
      out.write("	if(hidden){\r\n");
      out.write("		$(\"#popup\").show();\r\n");
      out.write("		$(\"#name\").html(take);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	  $(\".close\").click(function(){\r\n");
      out.write("	    $(\"#popup\").hide();\r\n");
      out.write("	  });\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
